### ISSUE TITLE
Collection method may cause incorrect counting of attempts when items are moved between bank and inventory (?)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#102]
Source: [WowAce](https://www.wowace.com/projects/rarity?comment=325)
> Moving Nat's Lucky Coins from bank to bags triggered completion on the mount and two pets I have yet to purchase. Only had 83 coins when this triggered.

See also: https://www.wowhead.com/item=117397/nats-lucky-coin#comments

**Comment by godejord** [comment]
I have not been able to reproduce this issue. The eventhandler specifically checks that the bank frame is not open  ( `not Rarity.isBankOpen` ) when updating the collection items. For this to have happened, the event "BANKFRAME_CLOSED" must somehow have been sent before the "BAG_UPDATE" event, which I don't know how is possible if the item came from the bank. Even so, I'm not sure it would affect the actual attempts anyway..

Because the collected items are handlet by "BAG_UPDATE", and if somehow the amount of collected items you have in your bag is higher than your recorded attempts, then the attempts will increase.
I.e. You have 83 of Nat's Lucky Coins in your bank but zero recorded attempts (maybe you installed Rarity after getting the coins). Then you will get 83 attempts after moving the items to your bag. 83 is more than what the pets cost, so these would then get flagged as complete I reckon, but that doesn't explain completion on the mount which costs 100.

**Comment by Duckwhale** [comment]
The detection of items in bags is somewhat unreliable, so it's not unthinkable something weird could happen. That said, without additional information we likely can't reproduce it.
