### ISSUE TITLE
Review item database and add missing waypoint data

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#327]
From Discord:
> And force some optional fields like coords.

Since the main window won't display any zone for items without waypoint data, it might be time to make this field mandatory. It doesn't need to have coordinates per se, but a ``mapID`` should exist to make sure a zone name is displayed in the UI.

It doesn't need to be perfectly accurate, as long as it's evident to the player where approximately they can get the item, in case they happen to be in the zone (and they may have hidden items "not in the current zone").

Needs to wait for #320 to be merged first.

**Comment by godejord** [comment]
May have to be creative with the Island Expedition items

**Comment by Duckwhale** [comment]
How so? Doesn't it suffice to simply add the expedition maps (and Boralus/the Horde capital if we care about the crates)?

**Comment by godejord** [comment]
Well, I don't have all the facts on Island Expeditions, but AFAIK some rewards are only tied to certain maps (not even thinking about the weekly creature types). For example the [Island Thunderscale](https://www.wowhead.com/item=166467/island-thunderscale) is believed to only drop from Jorundall. Ref [here](https://www.wowhead.com/island-expeditions-collection-rewards#commonrewards-thunderscale-dragons), and on the comment section of the item itself.

Currently I believe the tracking is just tracking all items on all Island Expedition maps, and updating every individual entry would be a major headache - and is bound to be incomplete or full of errors as the data just isn't there.
I guess adding the zones in a similar manner would be the most doable solution.. Add all maps for all items tied to Island Expedition. 

Then my initial thought was having zones display something like "Island Expeditions" instead of i.e. "Whispering Reef + 10", but I suppose that's just creating more work for no good reason.

**Comment by Duckwhale** [comment]
How about we take the lazy way out and add *only* Boralus/Dazar'alor?

Technically, this is where the expeditions are started from, and also where the crates can be purchased.

**Comment by godejord** [comment]
Sounds like a good compromise! 😅
