### ISSUE TITLE
Host the addon outside of CurseForge

### ISSUE THREAD

**Issue by JVemmer** [WowRarity/Rarity#460]
As CurseForge is locking out everyone except Overwolf's own addon manager (source: [https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912](https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912)), please host this addon elsewhere than CurseForge (at least co-host it elsewhere). Options include:

- Hosting a .zip file of the addon here in the GitHub repository (this allows WowUp to pull it down)
- Hosting it on WowUpHub website
- Hosting it on wago.io (allows monetization to continue, if that is a concern)
- Hosting it on TukUI
- Hosting it on WowInterface

I am personally using WowUp to update addons, and while I very much respect that some addon creators want their work monetized, and believe that they should have the option, I do not support the Overwolf lock-out simply because they want everyone to use their app. If monetization is a priority, I suggest using wago.io as addon hosting, as it allows for monetization of addons, also while using WowUp; which shows they're willing to find solutions, rather than the Overwolf approach of refusing to cooperate.
I don't mind anyone hosting their addons on CurseForge, but please, please, please host it outside of CurseForge as well, for those of us who would like to cut ties with CurseForge, but still use your amazing addon :heart:

**Comment by Duckwhale** [comment]
Hello! Since there's a few different concerns here, let me address them individually:

* Creating GitHub releases is something I wanted to do, but since Rarity has always been built on Curse/WowAce infrastructure that'd require a way to replace the CurseForge packager. While it doesn't sound like an easy task, I haven't spend much thought on it so far. Status: #307
* I wasn't aware you can host addons on WowUpHub. Is there a way to automate this? I haven't found any information on the site, but if it's possible to set up a pipeline that deploys to it I will happily do so
* After some internal discussions we have decided to not support wago.io and will not be publishing Rarity there
* Is there a significant user base on TukUI? It looked like it very much focuses on ElvUI and seemed rather fringe, to be honest. Either way, if deploying there can be automated I'm not opposed to it
* The same is pretty much true for WowInterface, with the addendum that I have tried to use it in the past and found it pretty dead and outdated. If there is now a way to publish releases more easily there I can look into it, but otherwise it seems like a waste of time

I've been wanting to move away from relying on just one vendor (CurseForge), especially with the various controversies and technical issues I've frequently encountered with their site. Unfortunately there's a lot of inertia here due to the way WoW addons have pretty much been vendor-locked for years, Blizzard's unwillingness to properly support the addon developer community, and the fact I don't really have the time to deal with all this on my own or even stay up-to-date with the happenings in the WOW ecosystem (I don't play the game and haven't really for many years).

That said, I fully support open-source and community-managed solutions like WowUp and would prefer everyone used those instead of proprietary (and arguably questionable) sites like Overwolf. Monetization has never been a concern, and will not stand in the way of providing a better user experience if I have any say in the matter.

I can bump up the priority of the aforementioned packaging issue and see if I can find some time to address it sooner rather than later, but if someone has some experience with automated deployments to the various platforms and can pitch in that'd likely save a ton of time (and that's the real issue because I'm extremely busy).

**Comment by Duckwhale** [comment]
Some relevant links to provide additional background:

* [WowUp Patreon post](https://www.patreon.com/posts/curseforge-62354064) about their application being denied
* [Overworlf Medium post](https://medium.com/overwolf/update-on-curseforge-api-180468476253) describing the API update

**Comment by Duckwhale** [comment]
I've set up an automated workflow that should publish all releases to CurseForge and GitHub (see https://github.com/WowRarity/Rarity/issues/307). WowUp users should be able to add the addon from its GitHub URL going forward.

Not sure about the other platforms, but if there is sufficient demand they could probably be added as well.

**Comment by JVemmer** [comment]
As long as any one of the above are used, I'm happy! If it's one or multiple, as long as WowUp can get to an updated version of the addon, I am a happy user 😄 
As for WowUpHub, it seems the documentation is pretty slim. However, with a quick glance through their [Discord](https://discord.gg/rk4F5aD), it seems that the way it works, is that you set up a GitHub repository in a specific manner, depending on what you want presented in WowUp, then write to the WowUp developers, and ask them to add your addon as installable. They are trying to avoid having to scan all of GitHub for "the right format", for addons to be shown, and its therefore a manual process. Their [Discord](https://discord.gg/rk4F5aD) is a very active place, with a lot of helpful people it seems.

**Comment by Duckwhale** [comment]
As instructed in their Discord, I have messaged the developer to inquire about adding the WowUpHub provider. As soon as they get back to me, I'll set things up so that you can find Rarity in the WowUp app even if the CurseForge provider is disabled (or dysfunctional).

Until then, you can add the addon by copy/pasting the GitHub repository URL and it should "just work", though it won't show up before manually added in this way in the event that CurseForge is unavailable.

I'll take the "wait and see" approach when it comes to WOWI and TukUI; the main goal was to ensure continued availability in a potential worst-case scenario (where CurseForge completely shuts out WowUp), which should hopefully be realized very soon :)
