### ISSUE TITLE
Add Dragonflight toys to the database

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#514]
Here is a list of new toys that should be looked into and potentially added. I have gone over the full list and filtered out irrelevant items.
Note that some of these are still missing drop rates, so could potentially be guaranteed drops; others have lacking sources at the moment. There just isn't enough data to find online yet

- [x] [Talisman of Sargha](https://www.wowhead.com/item=200857/talisman-of-sargha)
- [x] [Notfar's Favorite Food](https://www.wowhead.com/item=200160/notfars-favorite-food)
- [x] [Personal Shell](https://www.wowhead.com/item=198409/personal-shell)
- [x] [A Collection Of Me](https://www.wowhead.com/item=200148/a-collection-of-me)
- [x] [The Super Shellkhan Gang](https://www.wowhead.com/item=200999/the-super-shellkhan-gang)
- [x] [Primalist Prison](https://www.wowhead.com/item=200198/primalist-prison)
- [x] [Infected Ichor](https://www.wowhead.com/item=200178/infected-ichor)
- [x] [Mage's Chewed Wand](https://www.wowhead.com/item=200249/mages-chewed-wand)
- [ ] [Primal Invocation Quintessence](https://www.wowhead.com/item=200636/primal-invocation-quintessence)
- [ ] [Everlasting Horn of Lavaswimming](https://www.wowhead.com/item=200116/everlasting-horn-of-lavaswimming)
- [ ] [Generous Goblin Grenade](https://www.wowhead.com/item=200142/generous-goblin-grenade)

**Comment by cyriun** [comment]
Added a few of these here #541

**Comment by Duckwhale** [comment]
I just noticed one item that was added in that PR has a 50% drop rate on wowhead: https://www.wowhead.com/item=202042/aquatic-shades

Do we even need to track this? I assume @godejord filtered it out because of the drop rate. It can hardly be considered a "rarity"?

Sorry for not catching this sooner 👀

**Comment by Duckwhale** [comment]
> i believe the personal shell toy is also 50%

Some wowhead comments indicate the rare might be bugged. If Rarity shows repeated attempts then (many) people will believe it and continue killing the rare, wasting their time. Since the drop rate is also very high, it might be best to just remove this item?

**Comment by cyriun** [comment]
yeah just scrap it

**Comment by Duckwhale** [comment]
2 of the 3 remaining items seem to not be relevant after all, going by wowhead data.

[Everlasting Horn of Lavaswimming](https://www.wowhead.com/item=200116/everlasting-horn-of-lavaswimming): Seems to be awarded from an event, but I've no idea how to track it. Maybe this should be moved to a separate issue since it may require more in-depth investigation (and possibly new logic?).
